# This is a basic workflow to help you get started with Actions

name: Eggplant Runner Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Eggplant Runner
        uses: keysight-eggplant/eggplant-github-action@v1.0.19
        with:
            # The URL of Eggplant DAI server, http(s)://dai_server_hostname:portnumber
            serverURL: http://10.244.8.149:8000/
            # The ID of the Eggplant DAI test configuration that you want to run, e.g. 09c48b7d-fc5b-481d-af80-fcffad5d9587
            testConfigID: "42576fc1-8be4-4381-8fd8-19a8ffa820ac"
            # The name of the test config that you want to run
            # The client ID to use to authenticate with the Eggplant DAI server
            clientID: "client:dai:api:integration:4e5783c7-f87c-4d84-bdf3-1cebe5cc3197"
            # The client secret to use to authenticate with the Eggplant DAI server  [env var: DAI_CLIENT_SECRET; required]
            clientSecret: "z8hIUKNiOjtwTZzWhOKrbFlimQVWkfyW" 
            parameters: "github=こんにちは14 lokang"
