# This is a basic workflow to help you get started with Actions

name: Eggplant Runner Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Eggplant Runner
        uses: keysight-eggplant/eggplant-github-action@v1.0.19
        with:
          serverURL: http://10.244.8.149:8000/
          testConfigID: "3e6b2da1-8053-49ef-9316-e82f7dcd2486"
          clientID: "client:dai:api:integration:4e5783c7-f87c-4d84-bdf3-1cebe5cc3197"
          clientSecret: "z8hIUKNiOjtwTZzWhOKrbFlimQVWkfyW"       
          parameters: "jp=こんにちは";;"de=goreng2"
